import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";

const banner =
  `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Ensure build directory exists if in production or if we want to change dev output too
// But usually for dev we keep it in root or specific target. 
// User asked to output to build folder "when npm build" (which implies production usually).
// Let's change output directory to 'build/' for production.

const outfile = prod ? "build/main.js" : "main.js";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: outfile,
});

if (prod) {
  if (!fs.existsSync("build")) {
    fs.mkdirSync("build");
  }
  await context.rebuild();
  fs.copyFileSync("manifest.json", "build/manifest.json");
  fs.copyFileSync("styles.css", "build/styles.css");
  console.log("Build complete. Files output to build/");
  process.exit(0);
} else {
  await context.watch();
}
